# Generated by Django 5.0.3 on 2024-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='deleteme', max_length=100)),
                ('odds', models.IntegerField(default=500000)),
                ('tier', models.IntegerField(default=0)),
                ('place', models.IntegerField(default=404)),
                ('cut', models.BooleanField(default=False)),
                ('wd', models.BooleanField(default=False)),
                ('thru', models.CharField(default='deleteme', max_length=100)),
                ('ttl_score', models.IntegerField(default=404)),
                ('today_score', models.IntegerField(default=404)),
                ('r1_score', models.IntegerField(default=404)),
                ('r2_score', models.IntegerField(default=404)),
                ('r3_score', models.CharField(default='deleteme', max_length=100)),
                ('r4_score', models.CharField(default='deleteme', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='deleteme', max_length=100)),
                ('total_score', models.IntegerField(default=0)),
                ('golfer', models.ManyToManyField(related_name='team_golfer', to='pool.golfer')),
            ],
        ),
    ]
