# Generated by Django 5.0.3 on 2024-04-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='r1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='r2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='today_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='golfer',
            name='ttl_score',
            field=models.IntegerField(default=0),
        ),
    ]
