# Generated by Django 5.0.3 on 2024-04-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_alter_golfer_place_alter_golfer_r1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.IntegerField(default=100),
        ),
    ]
